"""empty message

Revision ID: 7138cb8991a0
Revises: 5ddf0aece6e3
Create Date: 2023-10-06 10:01:58.205164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7138cb8991a0'
down_revision = '5ddf0aece6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_group', schema=None) as batch_op:
        batch_op.alter_column('group_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_group', schema=None) as batch_op:
        batch_op.alter_column('group_description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
